language: c

os:
  - linux
  - osx

dist:
  - trusty
  - xenial

# osx_image: xcode9.3 # fail install of php
osx_image: xcode9.2

compiler:
  - clang
  - gcc


addons:
  apt:
    packages:
# only have check 0.9 on trusty.
#    - check
# Only have libusb-dev 0.1.. we want 0.9.1+
#    - libusb-dev
    - libavahi-client-dev
    - swig

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install swig; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install php; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install check; fi

before_script:
  - ./bootstrap

script:
  - ./configure && make -j 2
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then make check; fi
