name: test

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: echo debug info
      run: |
        echo "${{ toJson(runner) }}"
        dpkg -l | grep php
        echo "php" $(php-config --php-binary) $(php-config --version)
        echo "include" $(php-config --includes)
